#!/usr/bin/env bash
# Copy extension files to dist/ folder for Chrome extension
set -e
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="$ROOT_DIR/dist"

rm -rf "$DIST_DIR"
mkdir -p "$DIST_DIR"

# copy manifest from project root
if [ -f "$ROOT_DIR/manifest.json" ]; then
  cp -R "$ROOT_DIR/manifest.json" "$DIST_DIR/"
  echo "Using manifest from project root"
else
  echo "Warning: manifest.json not found in root"
fi

# copy extension scripts (generated by build:ts)
cp -R "$ROOT_DIR/public/background.js" "$DIST_DIR/"
cp -R "$ROOT_DIR/public/content.js" "$DIST_DIR/"

# copy popup HTML and script
cp -R "$ROOT_DIR/public/popup.html" "$DIST_DIR/"
cp -R "$ROOT_DIR/public/popup.js" "$DIST_DIR/"
echo "Copied popup files"

# copy icons directory
if [ -d "$ROOT_DIR/public/icons" ]; then
  cp -R "$ROOT_DIR/public/icons" "$DIST_DIR/"
  echo "Icons copied to dist/icons"
else
  echo "Warning: icons directory not found"
fi

echo "Dist prepared at $DIST_DIR"
